---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockchain-redis-deployment
  labels:
    app: blockchain-redis
    username: alexwitt
    env: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blockchain-redis
  template:
    metadata:
      labels:
        app: blockchain-redis
        username: alexwitt
        env: test
    spec:
      containers:
      - name: blockchain-redis
        image: redis:5.0.0
        volumeMounts:
        - name: blockchain-redis-pvc
          mountPath: "/data"
        ports:
        - name: redis
          containerPort: 6379
      volumes:
      - name: blockchain-redis-pvc
        persistentVolumeClaim:
          claimName: blockchain-redis-pvc
