---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blockchain-redis-pvc
  labels:
    username: alexwitt
    env: test
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: rbd
  resources:
    requests:
      storage: 1Gi
