---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-redis-service
  labels:
    username: alexwitt
    env: test
spec:
  type: ClusterIP
  selector:
    username: alexwitt
    env: test
    app: blockchain-redis
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
