---
apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  labels:
    username: alexwitt
    env: test
spec:
  type: ClusterIP
  selector:
    username: alexwitt
    env: test
    app: blockchain-transaction
  ports:
  - name: flask
    port: 5000
    targetPort: 5000
