---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alexwitt-hw7-flask-deployment
  labels:
    app: alexwitt-hw7-flask
    username: alexwitt
    env: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alexwitt-hw7-flask
  template:
    metadata:
      labels:
        app: alexwitt-hw7-flask
        username: alexwitt
        env: test
    spec:
      containers:
      - name: alexwitt-hw7-flask
        image: alexwitt23/coe332-hw07
        ports:
        - name: flask
          containerPort: 5000
        env:
        - name: "REDIS_IP"
          value: "10.103.175.2"
        imagePullPolicy: Always
        command: [ "python3", "api.py" ]
