---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-service
  labels:
    username: alexwitt
    env: test
spec:
  type: ClusterIP
  selector:
    username: alexwitt
    env: test
    app: blockchain-flask
  ports:
  - name: flask
    port: 5001
    targetPort: 5001
